### ISSUE TITLE
Nav menu?

### ISSUE THREAD

**Issue by zebequ** [gopatrik/space.js#12]
Hi... Very nice work!
Is it possible to use a navigation menu in addition to scroll, to reach a specific frame?

**Comment by gopatrik** [comment]
Not entirely sure if you mean possible for you to make or for me to add, but it is very possible; each frame object contains a ```distanceTo``` property containing the distance the frame has to the top of the page. It would be simple to have a menu where its items just triggers ```scrollTop([distance])```.

Cheers! :)

**Comment by zebequ** [comment]
Thank you for your kind answer...
I tried to do that, I saw the 'distanceTo' parameter and I put it in an array for every frame on init() event.
But when I call the scrollTop function with the relative distanceTo value, I don't reach the compete frame but the beginning of its transition... I think...
This is what I did, I don't know if I'm completely on the right way...

// give each frame an id
var frameId = "frame-"+index;
frame.id = frameId;
checkDistanceTo.push(distanceTo);

// at the end of init()
$(myNavSelector).on('click', function(event) {
var checkTarget = $(this).attr('section'); //this is a <a hre="#" section=""> value referring to the frame

event.preventDefault();

$('html, body').animate({scrollTop: checkDistanceTo[checkTarget]}, {duration:1200, easing:"easeInOutExpo"});
});

**Comment by gopatrik** [comment]
Ah yes, that takes you to the beginning of that transition; if you want to go to the midpoint of the frame transition you could just add half its height to the distanceTo; i.e something like ```scrollTop(frame.distanceTo + (frame.duration/2))```. frame.duration is called ```simulatedHeight`` in the init method!

Cheers!

**Comment by zebequ** [comment]
Ok... works!
Thank you so much...
